image: docker:latest            

services:
  - docker:dind          

variables:
  DOCKER_TLS_CERTDIR: ""        

stages:       
  - build
  - test
  - deploy

build-job:     
  stage: build
  script:
    - docker build -t my_image .

test-job:   
  stage: test
  script:
    - docker run --rm my_image 

deploy-job:      
  stage: deploy 
  environment: production
  script:
    - docker compose up -d
